# environment.yml - add testing dependencies
name: physics-suite
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - pandas>=1.3.0
  - h5py>=3.6.0
  - jupyter>=1.0.0
  - sympy>=1.8
  - scikit-learn>=1.0.0
  - qutip>=4.6.0
  - pytest>=6.0.0          # Add this
  - pytest-cov             # For coverage reports
  - black                  # Code formatting
  - pip
  - pip:
    # Local editable packages
    - -e ../lqg-first-principles-gravitational-constant
    - -e ../negative-energy-generator
    - -e .
    
    # Regular pip packages
    - torch>=1.9.0
    - scikit-optimize>=0.9.0
    - deap>=1.3.0
    - tqdm>=4.62.0
    - click>=8.0.0
    - pyyaml>=6.0.0